from pydantic import BaseModel, Field
from typing import List, Any, Optional

class NarrativeInput(BaseModel):
    """The expected incoming payload from a B2B client platform."""
    raw_text: str = Field(
        ..., 
        example="ice-cream, school, exhibition, pokemon, danger",
        description="The raw, chaotic, unstructured human brain-dump text."
    )
    client_id: str = Field(
        ..., 
        example="wattpad_internal_prod_01",
        description="The unique identifier of the B2B client platform making the request."
    )

class Entity(BaseModel):
    """A clean, isolated narrative asset extracted from the raw input."""
    name: str = Field(..., description="Name of the character, location, prop, or creature.")
    type: str = Field(..., description="Classification category (e.g., Protagonist, Spatial Trap, Relic).")
    description: str = Field(..., description="A detailed, cinematic overview of this asset's properties.")
    narrative_function: str = Field(..., description="The role this asset plays in creating conflict or advancing the plot.")

class ThreeActStructure(BaseModel):
    """Standard Hollywood narrative pacing engine layout."""
    act_1_setup: str = Field(..., description="The status quo, introduction of assets, and inciting incident.")
    act_2_confrontation: str = Field(..., description="Rising stakes, core conflicts, and the obstacles faced.")
    act_3_resolution: str = Field(..., description="The dramatic climax and the absolute final outcome.")

class NarrativeArchitecture(BaseModel):
    """The master plot mapping object."""
    inciting_incident: str = Field(..., description="The single moment that breaks the status quo and forces the plot forward.")
    three_act_structure: ThreeActStructure


class CinemaScenePrompt(BaseModel):
    """A highly descriptive prompt designed explicitly for text-to-image/video generative engines."""
    scene_number: int = Field(..., description="The sequence position (1, 2, or 3 corresponding to Acts I, II, III).")
    visual_description: str = Field(..., description="Detailed cinematic prompt specifying framing, lighting, atmosphere, and action. Do not use abstract text; focus strictly on visual elements.")
    aspect_ratio: str = Field(default="16:9", description="The required visual layout framing shape.")

class CinemaTrailerSpecs(BaseModel):
    """The collection of scene markers guiding our automated background generation loops."""
    trailer_title: str = Field(..., description="A punchy, commercial-ready teaser name for the trailer.")
    scenes: List[CinemaScenePrompt] = Field(..., description="Exactly 3 distinct scene descriptors matching the 3-Act structure.")

class NarrativeOutput(BaseModel):
    """The absolute final, validated JSON layout that B2B clients pay for."""
    primary_genre: str = Field(..., description="The most fitting cinematic genre calculated from the raw elements.")
    world_description: str = Field(..., description="Comprehensive rules, layout, and visual aesthetic of the setting.")
    entities: List[Entity] = Field(..., description="Array of safe, structured narrative components extracted by the engine.")
    narrative_architecture: NarrativeArchitecture = Field(..., description="The structured plot framework.")
    cinema_trailer_specs: CinemaTrailerSpecs = Field(..., description="The generated trailer specifications.")

    final_video_url: Optional[str] = Field(
        default=None, 
        description="The live server network access path hosting the stitched .mp4 video asset file."
    )
    
    compliance_logs: str = Field(
        default="No compliance logs generated.", 
        description="Legal and trademark filtration trail generated by the engine."
    )

### Auth classes for internal use only ###

class TokenData(BaseModel):
    username: Optional[str] = None


class User(BaseModel):
    username: str
    full_name: Optional[str] = None
    email: Optional[str] = None
    disabled: Optional[bool] = None


class UserInDB(User):
    hashed_password: str


class LoginRequest(BaseModel):
    username: str
    password: str
